# 端口号
server:
  port: 8082

# 调试a
debug:
  true

# 配置 mapper 地址
mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.132:3306/test?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
